### PR TITLE
required packages

### PR DESCRIPTION
**Pull request by 0zhu**
- added missing required packages and installation steps to the documentation

### CODE REVIEW

**Comment by oneumyvakin** [comment]
@zhubanRuban Hi! Thank you for your contribution! Could you please adjust commit message a little bit to make it more clear for future contributors like 'Add missed required packages to documentation'?

**Comment by 0zhu** [comment]
Thank you, done.

**Comment by oneumyvakin** [comment]
@zhubanRuban Don't see updates, have you forget to git push changes?

**Comment by 0zhu** [comment]
Yes, sorry! It is all set now.

**Pull request closed without merging**
